import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	up: {
		backgroundColor: 'white',
		marginTop: 43,
	},
	title: {
		height: 25,
		//fontFamily: "AppleSDGothicNeo",
		fontSize: 21,
		fontWeight: '600',
		fontStyle: 'normal',
		lineHeight: 25,
		letterSpacing: -0.67,
		//textAlign: 'left',
		//justifyContent: 'center',
		alignContent: 'center',
		marginBottom: 26,
	},
	middleContainer: {
		width: '100%',
		height: 31,
		backgroundColor: '#efefef',
		marginBottom: 24,
	},
	middleView: {
		width: '100%',
		height: 31,
		alignItems: 'center',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		marginHorizontal: 17,
	},
	martname: {
		height: 15,
		//fontFamily: "AppleSDGothicNeo",
		fontSize: 12,
		fontWeight: 'normal',
		fontStyle: 'normal',
		lineHeight: 15,
		letterSpacing: -0.38,
		textAlign: 'center',
		color: '#000000',
	},
	root: {
		flex: 1,
		backgroundColor: '#ffff',
	},
	item_container: {
		flexDirection: 'row',
		marginVertical: 8,
		marginHorizontal: 17,
	},
	image_container: {},
	detail_container: {
		flexDirection: 'column',
		marginLeft: 10,
	},
	last_container: {
		flexDirection: 'row',
	},
	barcode: {
		width: 139,
		//fontFamily: "AppleSDGothicNeo",
		fontSize: 11,
		fontWeight: '500',
		fontStyle: 'normal',
		lineHeight: 14,
		letterSpacing: 0,
		textAlign: 'left',
		color: '#000000',
		marginBottom: 8,
	},
	product_name: {
		width: 212,
		fontSize: 18,
		fontWeight: '500',
		fontStyle: 'normal',
		lineHeight: 28,
		letterSpacing: -0.43,
		textAlign: 'left',
		color: '#000000',
		marginBottom: 15,
	},
	product_price: {
		width: 72,
		fontSize: 17,
		fontWeight: '600',
		fontStyle: 'normal',
		lineHeight: 28,
		letterSpacing: -0.41,
		textAlign: 'left',
		color: '#d00404',
		marginRight: 99,
	},
	product_image: {
		width: 107,
		height: 90,
		//backgroundColor:'#123424',
		borderRadius: 5,
	},
	go_detail: {
		flexDirection: 'row',
		width: 62,
		opacity: 0.77,
		//fontFamily: "AppleSDGothicNeo",
		fontSize: 12,
		fontWeight: 'normal',
		fontStyle: 'normal',
		lineHeight: 28,
		letterSpacing: -0.29,
		textAlign: 'left',
		color: '#000000',
		alignItems: 'center',
	},
	go_detail_image: {
		width: 20,
		height: 20,
	},
	// deleteOver: {
	//   position: 'absolute',
	//   bottom: '15%',
	// 	width: 326,
	//   height: 60,
	//   borderRadius: 30,
	// 	//backgroundColor: 'transparent',
	// 	elevation: 0,
	// },
	// deleteView:{
	//   marginTop: 2,
	//   flexDirection: 'row',
	//   justifyContent: 'center',
	//   alignItems: 'center',
	// },
	// deleteText:{
	//   //width: 118,
	//   //height: 32,
	//   //fontFamily: "AppleSDGothicNeo",
	//   fontSize: 16,
	//   fontWeight: "600",
	//   fontStyle: "normal",
	//   //lineHeight: 19,
	//   letterSpacing: -0.51,
	//   textAlign: "center",
	//   color: "#000000",
	//   marginLeft: 6.2,
	// },
	// xbutton:{
	//   position: 'absolute',
	//   top : 4,
	//   right : 15,
	// }
});

export default styles;
