import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	root1: { backgroundColor: '#ffff', flex: 1 },
	root: {
		display: 'flex',
		flexDirection: 'column',
		flex: 1,
		backgroundColor: '#ffff',
	},
	yellowText: {
		marginTop: '4.9%',
		fontSize: 13,
		fontWeight: 'normal',
		fontStyle: 'normal',
		lineHeight: 16,
		letterSpacing: -0.13,
		color: '#e6a800',
		paddingBottom: 4,
	},
	header: {
		width: 156,
		height: 23,
		fontSize: 19,
		fontWeight: '600',
		fontStyle: 'normal',
		lineHeight: 23,
		letterSpacing: -0.61,
		textAlign: 'left',
		color: '#000000',
	},
	imageStyle: {
		width: '100%',
		height: 288,
		zIndex: 0,
	},
	backgroundShadowImage: {
		width: 375,
		height: 288,
		opacity: 0.2,
		position: 'absolute',
		backgroundColor: '#000000',
	},
	focusImage: {
		position: 'absolute',
		width: 239.3,
		height: 239.5,
		zIndex: 100,
	},
	ParentImage: {
		position: 'absolute',
	},
	flexbox1: {
		paddingBottom: 113,
		marginLeft: '6.9%',
	},
	flexbox2: {
		justifyContent: 'center',
		paddingTop: '13.2%',
		marginLeft: '24.6%',
	},
	guidefont1: {
		width: 28,
		height: 16,
		fontSize: 13,
		fontWeight: '600',
		fontStyle: 'normal',
		lineHeight: 16,
		letterSpacing: 0.13,
		textAlign: 'center',
		color: '#e6a800',
		marginRight: '4%',
	},
	guidefont2: {
		width: 136,
		height: 25,
		fontSize: 21,
		fontWeight: '600',
		fontStyle: 'normal',
		lineHeight: 25,
		letterSpacing: -0.21,
		textAlign: 'center',
		color: '#000000',
	},
	flexRow: {
		marginLeft: '6.4%',
		marginTop: '4.8%',
		justifyContent: 'flex-start',
		alignItems: 'center',
		display: 'flex',
		flexDirection: 'row',
	},
	flexRow2: {
		marginLeft: '6.4%',
		justifyContent: 'flex-start',
		alignItems: 'center',
		flexDirection: 'row',
	},
	flexBox: {
		flexDirection: 'row',
		width: '100%',
		flex: 1,
		marginTop: '78.9%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	font1: {
		fontSize: 16,
		fontStyle: 'normal',
		letterSpacing: -0.17,
		textAlign: 'left',
		alignSelf: 'center',
		color: '#000000',
	},
	font2: {
		fontSize: 16,
		fontWeight: 'bold',
		fontStyle: 'normal',
		letterSpacing: -0.17,
		textAlign: 'left',
		alignSelf: 'center',
		color: '#000000',
	},
	font3: {
		fontSize: 16,
		fontWeight: 'bold',
		fontStyle: 'normal',
		lineHeight: 25,
		letterSpacing: -0.17,
		textAlign: 'left',
		alignSelf: 'center',
		color: '#000000',
		backgroundColor: '#fade7f',
	},
	buttonStyle: {
		width: 350,
		height: 60,
		borderRadius: 24,
		backgroundColor: '#fbd145',
		borderStyle: 'solid',
		borderWidth: 1,
		borderColor: '#000000',
	},
	buttonTitleFont: {
		fontSize: 17,
		fontWeight: '500',
		fontStyle: 'normal',
		lineHeight: 20,
		letterSpacing: 0,
		textAlign: 'center',
		color: '#000000',
	},
	flexBox1: {
		flex: 1,
		width: '100%',
	},
});
